line_width: 100
tab_size: 2
separate_ctrl_name_with_space: true
separate_fn_name_with_space: false
dangle_parens: false
dangle_align: false

# Control how command args are split
max_subgroups_hwrap: 2
max_pargs_hwrap: 6

# Control argument alignment
enable_sort: true
autosort: true
line_ending: unix

# Style tweaks
keyword_case: lower
command_case: lower
