name: Docs

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (inside container)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            python3 python3-pip doxygen graphviz git
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx myst-parser furo breathe exhale

      - name: Build docs
        run: |
          chmod +x scripts/build_docs.sh
          SPHINX_STRICT=1 ./scripts/build_docs.sh --force -q

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build-docs/docs/html   # must contain index.html

  deploy:
    needs: docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
