name: Docs

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

# Ensure Bash inside containers (fixes: "Illegal option -o pipefail")
defaults:
  run:
    shell: bash

jobs:
  docs:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deps (apt) + Python venv
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache
        run: |
          set -euo pipefail
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            python3 python3-venv python3-pip doxygen graphviz git
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip wheel
          pip install sphinx myst-parser furo breathe exhale sphinxcontrib.mermaid

      - name: Build docs
        run: |
          set -euo pipefail
          . .venv/bin/activate
          chmod +x scripts/build_docs.sh
          SPHINX_STRICT=1 ./scripts/build_docs.sh --force -q

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build-docs/docs/html

  deploy:
    needs: docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
