name: Docs

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write 

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip doxygen graphviz
          pip install sphinx myst-parser furo breathe exhale

      - name: Configure and build docs
        run: |
          cmake -S . -B build -DBUILD_DOCS=ON
          cmake --build build --target docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-docss
          path: build/docs/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
