name: Docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install sphinx myst-parser furo

      - name: Build documentation
        working-directory: docs
        run: |
          sphinx-build -b html . _build/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html
