name: Linux CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    env:
      CC: ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang' }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ gfortran clang libopenmpi-dev

      - name: Configure (CMake)
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -j4

      - name: Run dummy solver
        run: |
          if [[ -f ./build/bin/solver ]]; then
            ./build/bin/solver
          else
            echo "⚠️  No solver binary yet (expected for dummy setup)."
          fi
