name: Tests · CPU/GPU/MPI (containerized)

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# Ensure Bash inside containers (fixes: "Illegal option -o pipefail")
defaults:
  run:
    shell: bash

jobs:
  prefetch-deps:
    name: Prefetch third-party archives
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install minimal build tools (inside container)
        run: |
          set -euo pipefail
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            ca-certificates git cmake ninja-build build-essential gfortran \
            python3 python3-venv python3-distutils python3-pip

      - name: Prefetch third-party sources into extern/
        run: |
          set -euo pipefail
          bash scripts/prefetch_third_party.sh

      - name: Upload extern/ cache for downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: extern-cache
          path: extern/
          if-no-files-found: error
          retention-days: 7

  gpu-warmup:
    name: GPU Warmup (NVIDIA container)
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: |
          docker pull nvidia/cuda:12.4.1-devel-ubuntu22.04
          docker run --rm --gpus all nvidia/cuda:12.4.1-devel-ubuntu22.04 nvidia-smi

  tests:
    name: ${{ matrix.name }}
    needs: prefetch-deps
    runs-on: ${{ matrix.runs_on }}
    container: ${{ fromJSON(matrix.container) }}
    timeout-minutes: 60
    continue-on-error: ${{ matrix.allow_fail || false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Unit (CPU)
            test: unit
            runs_on: ubuntu-latest
            container: '{"image":"ubuntu:24.04"}'

          - name: Perf (CPU)
            test: perf
            runs_on: ubuntu-latest
            container: '{"image":"ubuntu:24.04"}'

          - name: MPI (emulated)
            test: mpi
            runs_on: ubuntu-latest
            container: '{"image":"ubuntu:24.04"}'
            mpi_mode: emulate
            np: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch extern/ from prefetch job
        uses: actions/download-artifact@v4
        with:
          name: extern-cache
          path: extern/

      - name: Ensure extern/ exists (fallback safety)
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -d extern ] || [ -z "$(ls -A extern || true)" ]; then
            echo "extern/ missing, running prefetch_third_party.sh here as a fallback…"
            bash scripts/prefetch_third_party.sh
          fi
          ls -l extern || true

      - name: Install build toolchain (inside container)
        run: |
          set -euo pipefail
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            cmake ninja-build build-essential gfortran git

      - name: Install MPI (when needed)
        if: ${{ matrix.test == 'mpi' }}
        run: |
          set -euo pipefail
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            openmpi-bin libopenmpi-dev

      - name: CPU Unit tests
        if: ${{ matrix.test == 'unit' }}
        env:
          OFFLINE: "1"
        run: |
          set -euo pipefail
          ./scripts/run_unit_tests.sh

      - name: CPU Perf tests
        if: ${{ matrix.test == 'perf' && !contains(matrix.container, 'nvidia/cuda') }}
        env:
          OFFLINE: "1"
          ENABLE_CUDA: "OFF"
          CMAKE_BUILD_TYPE: Release
        run: |
          set -euo pipefail
          ./scripts/run_perf_tests.sh

      - name: MPI tests (emulated on CI)
        if: ${{ matrix.test == 'mpi' }}
        env:
          OFFLINE: "1"
        run: |
          set -euo pipefail
          ./scripts/run_mpi_tests.sh --mode ${{ matrix.mpi_mode || 'auto' }} --np ${{ matrix.np || 4 }} --keep-going

      - name: Upload test reports (JUnit XML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.name }} · reports
          path: |
            build-unit/test-reports/unit/**
            build-perf/test-reports/perf/**
            build-mpi/test-reports/mpi/**
          if-no-files-found: ignore
          retention-days: 7

  tests-gpu:
    name: Perf (GPU)
    needs: [prefetch-deps, gpu-warmup]   
    runs-on: [self-hosted, linux, x64]

    container:
      image: nvidia/cuda:12.4.1-devel-ubuntu22.04
      options: --gpus all

    timeout-minutes: 60
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download extern cache
        uses: actions/download-artifact@v4
        with:
          name: extern-cache
          path: extern/
        continue-on-error: true

      - name: Install build deps
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            cmake ninja-build build-essential gfortran git

      - name: Install newer CMake via pip (alt)
        run: |
          apt-get update && apt-get install -y --no-install-recommends python3-pip
          python3 -m pip install --upgrade cmake ninja
          cmake --version

      - name: GPU info
        run: |
          nvidia-smi || true
          nvcc --version || true

      - name: Run perf tests (GPU)
        env:
          OFFLINE: "1"              
          CMAKE_BUILD_TYPE: Release
        run: |
          ./scripts/run_perf_tests.sh

      - name: Upload test reports (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Perf (GPU) · reports
          path: build-perf/test-reports/perf/**
          if-no-files-found: ignore
          retention-days: 7
